version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 368355641188.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/nodejs-ram
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"nest-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json